### ISSUE TITLE
测试了一下CTP的，好像OnRspQryInstrument返回的InstrumentField值有问题

### ISSUE THREAD

**Issue by liaom** [QuantBox/QuantBox_XAPI#1]
![iuaxl jfrnqk ol 784r1it](https://cloud.githubusercontent.com/assets/3195461/5789715/01e3b836-9eb1-11e4-919c-421ce15e5e4b.png)

test_CTP_Main里面添加
api.OnRspQryInstrument = OnRspQryInstrument;和
api.ReqQryInstrument("","");
打出来的InstrumentName全是交易所代码,InstrumentID全是日期

又测试了一下其他命令，好像C++返回的struct到了C#里都有问题。

另外
MsgQueue.cpp里面
void CMsgQueue::StopThread()
{
    //m_mtx.lock();

```
m_bRunning = false;
lock_guard<mutex> cl(m_mtx);
if(m_hThread)
{
    m_hThread->join();
    delete m_hThread;
    m_hThread = nullptr;
}
//m_mtx.unlock();
```

}
和
void CMsgQueue::RunInThread()
{
    while (m_bRunning)
    {
        if (Process())
        {
        }
        else
        {
            //挂起，等事件到来
            //m_mtx.lock();
            this_thread::sleep_for(chrono::milliseconds(1));
        }
    }

```
lock_guard<mutex> cl(m_mtx);

// 清理线程
m_hThread = nullptr;
m_bRunning = false;
```

}
的两个lock_guard是不是会产生死锁？

**Comment by wukan1986** [comment]
请测32位的，64位的有问题

发自我的 iPad

**Comment by wukan1986** [comment]
lock_guard只是让这块代码区在重复调用时锁定，并不会出问题

**Comment by liaom** [comment]
问题是stopthread的lock_guard后又有一个join，如果此时runinthread正好执行到lock_guard之前就执行不下去了吧

刚才用win32重新build了一下，还是一样的问题

**Comment by wukan1986** [comment]
你是想说lock_guard在运行过程中嵌套了吧？
这个地方StopThread中加锁了，然后在RunInThread想退出线程时又想获得这个锁，这个地方对lock_guard对同一对象加锁的机制我也是不很擅长，如果要删的话那就是得删了RunInThread中的这一句。

CTP在6.3.5版时发布了64位，然后我把头文件、库、dll全换成6.3.5版的，后又发布了6.3.6，但不带64位，不过我已经把头文件、库给换了，这下导致编译64位表面看没问题，但C层数据全是错的，不过我又不想同时维护两套，设置两套编译选项，所以只选32位就成了。这个是不会错的。

**Comment by liaom** [comment]
是我的ctp版本用错了，换成6.3.6就没问题了

**Comment by lililililililili** [comment]
6.3.6的64位的CTP已经有了，能更新一下64位的版本么？谢谢！
