### ISSUE TITLE
飞马交易登录时提示heap corruption detected

### ISSUE THREAD

**Issue by liaom** [QuantBox/QuantBox_XAPI#12]
好像是执行到ReqQryUserInvestor时，CMsgQueue::Process()在delete ptr1时出错
![qq 20150312230600](https://cloud.githubusercontent.com/assets/3195461/6620746/62b957de-c90d-11e4-8c28-c4c869c833c7.png)

**Comment by liaom** [comment]
strncpy(pBody->UserID, m_UserInfo.UserID, sizeof(TUstpFtdcInvestorIDType));
中的TUstpFtdcInvestorIDType应改成TUstpFtdcUserIDType

**Comment by wukan1986** [comment]
多谢，TUstpFtdcUserIDType已经改
