### ISSUE TITLE
飞马行情接口连接成功，但是没有最后一步OnRspLoginUserLogin回调

### ISSUE THREAD

**Issue by lemonsoda** [QuantBox/QuantBox_XAPI#13]
OnConnectionStatus函数依次如下被回调：
Initialized
Connecting
Connected
Logining
然后后面就没了

**Comment by lemonsoda** [comment]
解决了，原来是TopicId没填写就会导致登陆不回调

**Comment by mepwang** [comment]
既然解决了就关闭这个issue吧
