### ISSUE TITLE
QuantBox.XAPI_Linux工程遗忘了Interface目录

### ISSUE THREAD

**Issue by mepwang** [QuantBox/QuantBox_XAPI#2]
环境：Linux Mint 17-64bit，Mono Develop 5.7
现象： 编译出错，显示 using QuantBox.XAPI.Interface错误

解决办法：在工程中增加Interface目录及目录先的所有源文件。

**Comment by wukan1986** [comment]
哦，不好意思，Interface这个接口还只是测试。
因为这个做成了C++转C#的库了，但我还有一些需求是直接用上C#库，所以预留了一下，还具体还没想好，所以导致Linux下不同步。

**Comment by mepwang** [comment]
已解决
