### ISSUE TITLE
商品期货CTP无法正确获得昨仓

### ISSUE THREAD

**Issue by renkun-ken** [QuantBox/QuantBox_XAPI#25]
例如一个账号持有rb1601 今仓30手多，昨仓5手多，但是`OnRspQryInvestorPosition`获得的仓位只有今仓，昨仓显示为0，在快期中可以正确获得昨仓。

**Comment by wukan1986** [comment]
同一合约会收到多个响应

**Comment by renkun-ken** [comment]
一种合约只收到一个PositionField的响应，rb1601只收到一个PositionField，其中

Position = 35, TdPosition = 35, YdPosition = 0

而从快期来看该账号的实际持仓为今仓35， 昨仓5.

**Comment by renkun-ken** [comment]
以前收中金所的IF IH IC时都是一个合约收到多个响应，但是商品上面就有很多问题，这边实盘账号持仓rb收的就不对，1个合约只能收到1个响应，以前还有RM等合约也有这种问题。

**Comment by renkun-ken** [comment]
在QuantBox.XAPI项目中测试，对于同时持有昨仓和今仓的rb可以返回多个持仓记录，但也都是今仓，昨仓的数据都没有返回。
