### ISSUE TITLE
为什么没有考虑将批量订阅的接口公开出来呢？

### ISSUE THREAD

**Issue by AndrewTsao** [QuantBox/QuantBox_XAPI#29]
CTP Subscribe 支持instrument set的参数，为什么在XAPI的设计的时候，把这个接口屏蔽了呢？
这样，如果考虑订阅全市场的时候，一个一个的订阅，效率上是否有会有影响？

**Comment by renkun-ken** [comment]
合约名称直接分号间隔不就可以吗？

**Comment by AndrewTsao** [comment]
嗯，后边研究出来了。可以批量订阅的。
