### ISSUE TITLE
在Linux上编译，出现cannot find -lQuantBox_Queue

### ISSUE THREAD

**Issue by mepwang** [QuantBox/QuantBox_XAPI#3]
环境：Linux Mint 17-64bit，Code::Blocks 13.12
现象：多数工程出现cannot find -lQuantBox_Queue链接错误。

应该是项目设置的路径问题吧，我看到libQuantBox_Queue.so已经生成了。

你有没有一个跨平台的持续集成环境啊？这样每天每个平台可以自动化的编译和单元测试，
能省不少事情。

**Comment by wukan1986** [comment]
是路径问题，我是把它复制在了/usr/lib下了

**Comment by mepwang** [comment]
已解决
