### ISSUE TITLE
hash_map在 linux下编译错误

### ISSUE THREAD

**Issue by mepwang** [QuantBox/QuantBox_XAPI#4]
环境：LinuxMint 17.1-64bit
现象： hash_map编译错误

描述： 
在Linux下hash_map的实现和VC++上稍有不同，在使用hash_map的文件中增加下面的语句： 

using namespace __gnu_cxx;

namespace __gnu_cxx
{
    template<> struct hash<const string>
    {
        size_t operator()(const string& s) const
        { return hash<const char*>()( s.c_str() ); } //__stl_hash_string
    };
    template<> struct hash<string>
    {
        size_t operator()(const string& s) const
        { return hash<const char*>()( s.c_str() ); }
    };
}

**Comment by wukan1986** [comment]
感谢提醒，我在windows下已经都换成unordered_map了，linux下可能是哪个地方没有注意，没改吧。

**Comment by mepwang** [comment]
今天更新了代码，hash_map已经被移除
