### ISSUE TITLE
QuantBox.XAPI/include/toolkit.cpp中OutputDebugStringA未定义

### ISSUE THREAD

**Issue by mepwang** [QuantBox/QuantBox_XAPI#7]
QuantBox.XAPI/include/toolkit.cpp中OutputDebugStringA未定义

**Comment by wukan1986** [comment]
晕，忘了这是Windows下特有的函数，为了输出日志到DebugView下。
因为有客户提出如何测OpenQuant到API的速度。这个地方我得加一下条件编译

**Comment by mepwang** [comment]
resolved
