### ISSUE TITLE
速度没有达到自己所想

### ISSUE THREAD

**Issue by wukan1986** [QuantBox/QuantBox_XAPI#8]
目前C#层返回的数据太慢。

我先现的想法是先把消息队列给改了，弄成内存池。
力争减少复制。

但从C++到C#还是太慢。

欢迎大家提供意见。

**Comment by mepwang** [comment]
有没有做一下Profiling看看哪里慢？
一般来说 ，不论是内存的复制还是C#自身，都不会太慢，
会不会是软件结构的问题？

**Comment by mepwang** [comment]
在Linux Mint 17.1 64-bit上用mono做了Profiling，节选结果附后。
测试代码是我自己写的，主要调用了ReqQryInstrument和Subscribe
注意到其中耗时最长的是（应该超过了95%的时间吧）：
39990    39990         80 unknown method 0x7f5200022150
我猜测是本地方法调用在耗时。
我觉得可能是C++库中的线程通信问题，等我有时间对库做Profiling看看
时间都被消耗到哪里了。

Method call summary
Total(ms) Self(ms)      Calls Method name
   40621        0         10 (wrapper runtime-invoke) <Module>:runtime_invoke_void__this___object (object,intptr,intptr,intptr)
   40620        0          1 unknown method 0x1436278
   40620        0          1 unknown method 0x143d860
   40620        0          1 unknown method 0x143d888
   40620        0          1 unknown method 0x143dd20
   40620        0          1 unknown method 0x14068f0
   40619        0          1 QuantBox.XAPI.NetQuote:<NetQuote>m__0 ()
   40010        0          1 System.Collections.Concurrent.BlockingCollection`1:Take ()
   40010        0          1 System.Collections.Concurrent.BlockingCollection`1:Take (System.Threading.CancellationToken)
   40010        1          1 System.Collections.Concurrent.BlockingCollection`1:TryTake (T&,int,System.Threading.CancellationToken,bool)
   40004        1         81 System.Threading.ManualResetEventSlim:Wait (int,System.Threading.CancellationToken)
   39992        1         80 unknown method 0x13a94a8
   39990    39990         80 unknown method 0x7f5200022150
    1707        1        305 (wrapper native-to-managed) QuantBox.XAPI.Callback.BaseApi:_OnRespone (byte,intptr,intptr,double,double,intptr,int,intptr,int,intptr,int)
    1705        1        305 QuantBox.XAPI.Callback.BaseApi:_OnRespone (byte,intptr,intptr,double,double,intptr,int,intptr,int,intptr,int)
    1423        1        296 QuantBox.XAPI.Callback.XApi:OnRespone (byte,intptr,intptr,double,double,intptr,int,intptr,int,intptr,int)
    1420        2        295 QuantBox.XAPI.Callback.XApi:_OnRspQryInstrument (intptr,int,double)
    1399        6        295 QuantBox.XAPI.NetTrade:OnRspQryInstrument (object,QuantBox.XAPI.InstrumentField&,int,bool)
    1003        2        899 unknown method 0x7f51d400aeb0
    1000       28        899 unknown method 0x7f51d400ae60
     957        3        598 unknown method 0x7f51d400aed8

**Comment by wukan1986** [comment]
条件变量肯定是要花时间等待的。
我这边测的主要是从C到C#这层的结构体封送有些慢。

内存池有什么推荐的没我找了找tcmalloc和nedmalloc，都没用过，了解得比较少。

**Comment by depend** [comment]
你测试的延迟是多少, 期望是多少?

**Comment by fouvy** [comment]
他主要是跟C/C++原生的速度比...

**Comment by depend** [comment]
封装成C#应该是因为下游应用也是.NET的，我比较好奇struct的传送以及pinvoke的延迟在整个系统里的延迟占多大的比例，是否值得优化。

**Comment by fouvy** [comment]
此处应该是比 .net 自己内部传数据 都还慢 具体的没有测试 wukan应该有测试数据的.

**Comment by mepwang** [comment]
现在有了C++版接口，这个issue关闭吧
