### ISSUE TITLE
能编译, 跑不起来

### ISSUE THREAD

**Issue by jackyjqzhang** [QuantBox/QuantBox_XAPI#9]
您好, 调试QuantBox.XAPI.exe, 运行到test_CTP_Main(string[] args) 里面的api.Connect()出错了, 说找不到thosttraderapi.dll. 在QuantBox.XAPI项目里面添加Referrence, ..\include\CTP\win32\thosttraderapi.dll, vs2013报错说无法添加. 请问该怎么处理? 谢谢!

**Comment by mepwang** [comment]
这不是Bug
把thosttraderapi.dll放到QuantBox.XAPI.exe能找到的目录。
